#+ endpoint http://opencitations.net/index/sparql

PREFIX cito: <http://purl.org/spar/cito/>
SELECT ?cited 
WHERE {
  <http://dx.doi.org/10.1162/qss_a_00023> ^cito:hasCitingEntity/cito:hasCitedEntity ?cited
}
